apiVersion: v2
appVersion: 4.6.7.0
dependencies:
- name: common
  repository: file://../../../library/common/2112.0.0
  version: 2112.0.0
description: Emby Server
home: https://emby.media/
icon: https://images-na.ssl-images-amazon.com/images/I/41NwssJC1iL.png
keywords:
- emby
name: emby
sources:
- https://hub.docker.com/r/emby/embyserver
upstream_version: 2.1.0
version: 1.0.0
